name: client-component-tests

services:
  component-tests:
    build:
      context: .
      dockerfile: Dockerfile.component-test
    platform: linux/amd64
    shm_size: 1gb 
    volumes:
      - ./:/app/client
      - node_modules:/app/client/node_modules
      - pnpm_store:/pnpm-store
    environment:
      - npm_config_store_dir=/pnpm-store

volumes:
  node_modules:
  pnpm_store:
