version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: hospital-test-db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: HospitalDB
    ports:
      - "5432:5432"
    volumes:
      - ./initScripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
