<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Postgres\**" />
    <Compile Remove="DTOs\Postgres\**" />
    <Compile Remove="Mapping\Postgres\**" />
    <Compile Remove="Models\Postgres\**" />
    <Content Remove="Data\Postgres\**" />
    <Content Remove="DTOs\Postgres\**" />
    <Content Remove="Mapping\Postgres\**" />
    <Content Remove="Models\Postgres\**" />
    <EmbeddedResource Remove="Data\Postgres\**" />
    <EmbeddedResource Remove="DTOs\Postgres\**" />
    <EmbeddedResource Remove="Mapping\Postgres\**" />
    <EmbeddedResource Remove="Models\Postgres\**" />
    <None Remove="Data\Postgres\**" />
    <None Remove="DTOs\Postgres\**" />
    <None Remove="Mapping\Postgres\**" />
    <None Remove="Models\Postgres\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>
	
</Project>
