// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type HospitalApiDtosExternalMedicineDetailOutputDto = {
    navn?: null | string;
    varenummer?: null | string;
    styrke?: null | string;
    pakning?: null | string;
    virksomtStof?: null | string;
    firma?: null | string;
    atcKode?: null | string;
    dosisdispensering?: boolean;
    udleveringsgruppe?: null | string;
    prisPrPakning?: null | string;
    prisPrEnhed?: null | string;
    aip?: null | string;
    tilskudBeregnesAf?: null | string;
    udgaaet?: boolean;
    udgaaetDato?: null | string;
    dosering?: null | string;
    indikation?: null | string;
    trafikAdvarsel?: boolean;
    ddd?: null | string;
    opbevaringsbetingelser?: null | string;
    nbsSpeciale?: null | string;
    haandkoeb?: boolean;
    tilskudKode?: null | string;
    tilskudTekst?: null | string;
};

export type HospitalApiDtosExternalMedicineProductOutputDto = {
    navn: string;
    varenummer: string;
    firma: string;
    styrke: string;
    detaljer: string;
    pakning: string;
};

export type HospitalApiDtosInputsDepartmentInputDto = {
    name?: null | string;
    type?: null | string;
};

export type HospitalApiDtosInputsFloorInputDto = {
    name?: string;
    fkBuildingId?: number | string;
};

export type HospitalApiDtosInputsLoginInputDto = {
    username?: string;
    password?: string;
};

export type HospitalApiDtosInputsMedicationInputDto = {
    name?: null | string;
    genericName?: null | string;
    brand?: null | string;
    form?: null | string;
    strength?: null | string;
    category?: null | string;
    description?: null | string;
};

export type HospitalApiDtosInputsMedicationStorageInputDto = {
    fkMedicationId?: number | string;
    amount?: number | string;
};

export type HospitalApiDtosInputsMedicationStorageMissingInputDto = {
    fkMedicationStorageId?: number | string;
    amountMissing?: number | string;
    wentMissingAt?: string;
};

export type HospitalApiDtosInputsPatientInputDto = {
    firstname?: null | string;
    lastname?: null | string;
    gender?: null | string;
    cprNumber?: null | string;
};

export type HospitalApiDtosInputsPrescriptionInputDto = {
    fkMedicationId?: number | string;
    fkTreatmentId?: number | string;
    fkPrescribedByStaffId?: number | string;
    doses?: number | string;
};

export type HospitalApiDtosInputsRegisterInputDto = {
    username?: string;
    password?: string;
    fkStaffId?: number | string;
};

export type HospitalApiDtosInputsRoomBookingInputDto = {
    fkRoomId?: number | string;
    startTime?: string;
    endTime?: string;
    fkPatientId?: number | string;
};

export type HospitalApiDtosInputsShiftInputDto = {
    startTime?: string;
    endTime?: string;
};

export type HospitalApiDtosInputsStaffInputDto = {
    firstname?: null | string;
    lastname?: null | string;
    fkRoleId?: number | string;
};

export type HospitalApiDtosInputsTreatmentInputDto = {
    fkPatientId?: number | string;
    description?: null | string;
    time?: string;
};

export type HospitalApiDtosInputsTreatmentStaffInputDto = {
    fkTreatmentId?: number | string;
    fkStaffId?: number | string;
};

export type HospitalApiDtosOutputsBuildingOutputDto = {
    id?: number | string;
    name?: string;
    address?: null | string;
};

export type HospitalApiDtosOutputsDepartmentOutputDto = {
    id?: number | string;
    name?: null | string;
    type?: null | string;
};

export type HospitalApiDtosOutputsFloorOutputDto = {
    id?: number | string;
    name?: string;
    fkBuildingId?: number | string;
};

export type HospitalApiDtosOutputsFloorRoomsOutputDto = {
    floor: HospitalApiDtosOutputsFloorOutputDto;
    rooms: Array<HospitalApiDtosOutputsRoomOutputDto>;
};

export type HospitalApiDtosOutputsLocationOutputDto = {
    building: HospitalApiDtosOutputsBuildingOutputDto;
    floorsWithRooms: Array<HospitalApiDtosOutputsFloorRoomsOutputDto>;
};

export type HospitalApiDtosOutputsLoginOutputDto = {
    token: string;
    staffId?: number | string;
    firstname?: null | string;
    lastname?: null | string;
    role?: string;
};

export type HospitalApiDtosOutputsMedicationOutputDto = {
    id?: number | string;
    name?: null | string;
    genericName?: null | string;
    brand?: null | string;
    form?: null | string;
    strength?: null | string;
    category?: null | string;
    description?: null | string;
};

export type HospitalApiDtosOutputsMedicationStorageMissingOutputDto = {
    id?: number | string;
    fkMedicationStorageId?: number | string;
    amountMissing?: number | string;
    wentMissingAt?: string;
};

export type HospitalApiDtosOutputsMedicationStorageOutputDto = {
    id?: number | string;
    fkMedicationId?: number | string;
    amount?: number | string;
};

export type HospitalApiDtosOutputsPatientOutputDto = {
    id?: number | string;
    firstname?: null | string;
    lastname?: null | string;
    gender?: null | string;
    cprNumber?: null | string;
};

export type HospitalApiDtosOutputsPrescriptionOutputDto = {
    id?: number | string;
    fkMedicationId?: number | string;
    fkTreatmentId?: number | string;
    fkPrescribedByStaffId?: number | string;
    doses?: number | string;
};

export type HospitalApiDtosOutputsRoomBookingOutputDto = {
    id?: number | string;
    fkRoomId?: number | string;
    startTime?: string;
    endTime?: string;
    fkPatientId?: number | string;
};

export type HospitalApiDtosOutputsRoomOutputDto = {
    id?: number | string;
    name?: string;
    fkFloorId?: number | string;
};

export type HospitalApiDtosOutputsShiftOutputDto = {
    id?: number | string;
    startTime?: string;
    endTime?: string;
};

export type HospitalApiDtosOutputsStaffOutputDto = {
    id?: number | string;
    firstname?: null | string;
    lastname?: null | string;
    fkRoleId?: number | string;
};

export type HospitalApiDtosOutputsTreatmentOutputDto = {
    id?: number | string;
    fkPatientId?: number | string;
    description?: null | string;
    time?: string;
};

export type HospitalApiDtosOutputsTreatmentStaffOutputDto = {
    id?: number | string;
    fkTreatmentId?: number | string;
    fkStaffId?: number | string;
};

export type HospitalApiDtosOutputsUserOutputDto = {
    id?: number | string;
    username?: string;
    fkStaffId?: number | string;
};

export type MicrosoftAspNetCoreMvcProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type AuthLoginData = {
    body: HospitalApiDtosInputsLoginInputDto;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type AuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: MicrosoftAspNetCoreMvcProblemDetails;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsLoginOutputDto;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type DepartmentGetAllDepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Department';
};

export type DepartmentGetAllDepartmentsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsDepartmentOutputDto>;
};

export type DepartmentGetAllDepartmentsResponse = DepartmentGetAllDepartmentsResponses[keyof DepartmentGetAllDepartmentsResponses];

export type DepartmentPostData = {
    body: HospitalApiDtosInputsDepartmentInputDto;
    path?: never;
    query?: never;
    url: '/api/Department';
};

export type DepartmentPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DepartmentDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Department/{id}';
};

export type DepartmentDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DepartmentGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Department/{id}';
};

export type DepartmentGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsDepartmentOutputDto;
};

export type DepartmentGetResponse = DepartmentGetResponses[keyof DepartmentGetResponses];

export type DepartmentPutData = {
    body: HospitalApiDtosInputsDepartmentInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Department/{id}';
};

export type DepartmentPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ExternalMedicinePricesGetMedicineProductsByNameData = {
    body?: never;
    path?: never;
    query?: {
        productName?: string;
    };
    url: '/api/ExternalMedicinePrices/productsByName';
};

export type ExternalMedicinePricesGetMedicineProductsByNameErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type ExternalMedicinePricesGetMedicineProductsByNameError = ExternalMedicinePricesGetMedicineProductsByNameErrors[keyof ExternalMedicinePricesGetMedicineProductsByNameErrors];

export type ExternalMedicinePricesGetMedicineProductsByNameResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosExternalMedicineProductOutputDto;
};

export type ExternalMedicinePricesGetMedicineProductsByNameResponse = ExternalMedicinePricesGetMedicineProductsByNameResponses[keyof ExternalMedicinePricesGetMedicineProductsByNameResponses];

export type ExternalMedicinePricesGetMedicineProductsByIngredientsData = {
    body?: never;
    path?: never;
    query?: {
        ingredientName?: string;
    };
    url: '/api/ExternalMedicinePrices/productsByIngredient';
};

export type ExternalMedicinePricesGetMedicineProductsByIngredientsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type ExternalMedicinePricesGetMedicineProductsByIngredientsError = ExternalMedicinePricesGetMedicineProductsByIngredientsErrors[keyof ExternalMedicinePricesGetMedicineProductsByIngredientsErrors];

export type ExternalMedicinePricesGetMedicineProductsByIngredientsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosExternalMedicineProductOutputDto;
};

export type ExternalMedicinePricesGetMedicineProductsByIngredientsResponse = ExternalMedicinePricesGetMedicineProductsByIngredientsResponses[keyof ExternalMedicinePricesGetMedicineProductsByIngredientsResponses];

export type ExternalMedicinePricesGetMedicineProductDetailsData = {
    body?: never;
    path?: never;
    query?: {
        productDetailId?: string;
    };
    url: '/api/ExternalMedicinePrices/productDetails';
};

export type ExternalMedicinePricesGetMedicineProductDetailsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type ExternalMedicinePricesGetMedicineProductDetailsError = ExternalMedicinePricesGetMedicineProductDetailsErrors[keyof ExternalMedicinePricesGetMedicineProductDetailsErrors];

export type ExternalMedicinePricesGetMedicineProductDetailsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosExternalMedicineDetailOutputDto;
};

export type ExternalMedicinePricesGetMedicineProductDetailsResponse = ExternalMedicinePricesGetMedicineProductDetailsResponses[keyof ExternalMedicinePricesGetMedicineProductDetailsResponses];

export type LocationGetAllLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Location';
};

export type LocationGetAllLocationsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type LocationGetAllLocationsError = LocationGetAllLocationsErrors[keyof LocationGetAllLocationsErrors];

export type LocationGetAllLocationsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsLocationOutputDto;
};

export type LocationGetAllLocationsResponse = LocationGetAllLocationsResponses[keyof LocationGetAllLocationsResponses];

export type LocationGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/{id}';
};

export type LocationGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type LocationGetError = LocationGetErrors[keyof LocationGetErrors];

export type LocationGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsLocationOutputDto;
};

export type LocationGetResponse = LocationGetResponses[keyof LocationGetResponses];

export type LocationGetAllFloorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Location/floor';
};

export type LocationGetAllFloorsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type LocationGetAllFloorsError = LocationGetAllFloorsErrors[keyof LocationGetAllFloorsErrors];

export type LocationGetAllFloorsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsFloorRoomsOutputDto;
};

export type LocationGetAllFloorsResponse = LocationGetAllFloorsResponses[keyof LocationGetAllFloorsResponses];

export type LocationPostFloorData = {
    body: HospitalApiDtosInputsFloorInputDto;
    path?: never;
    query?: never;
    url: '/api/Location/floor';
};

export type LocationPostFloorResponses = {
    /**
     * OK
     */
    200: number | string;
};

export type LocationPostFloorResponse = LocationPostFloorResponses[keyof LocationPostFloorResponses];

export type LocationDeleteFloorData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/floor/{id}';
};

export type LocationDeleteFloorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LocationGetFloorData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/floor/{id}';
};

export type LocationGetFloorErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type LocationGetFloorError = LocationGetFloorErrors[keyof LocationGetFloorErrors];

export type LocationGetFloorResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsFloorRoomsOutputDto;
};

export type LocationGetFloorResponse = LocationGetFloorResponses[keyof LocationGetFloorResponses];

export type LocationPutFloorData = {
    body: HospitalApiDtosInputsFloorInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/floor/{id}';
};

export type LocationPutFloorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MedicinGetAllMedicinsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Medicin';
};

export type MedicinGetAllMedicinsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type MedicinGetAllMedicinsError = MedicinGetAllMedicinsErrors[keyof MedicinGetAllMedicinsErrors];

export type MedicinGetAllMedicinsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationOutputDto;
};

export type MedicinGetAllMedicinsResponse = MedicinGetAllMedicinsResponses[keyof MedicinGetAllMedicinsResponses];

export type MedicinPostData = {
    body: HospitalApiDtosInputsMedicationInputDto;
    path?: never;
    query?: never;
    url: '/api/Medicin';
};

export type MedicinPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MedicinDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Medicin/{id}';
};

export type MedicinDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MedicinGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Medicin/{id}';
};

export type MedicinGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type MedicinGetError = MedicinGetErrors[keyof MedicinGetErrors];

export type MedicinGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationOutputDto;
};

export type MedicinGetResponse = MedicinGetResponses[keyof MedicinGetResponses];

export type MedicinPutData = {
    body: HospitalApiDtosInputsMedicationInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Medicin/{id}';
};

export type MedicinPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MissingStorageGetAllMedicationStorageMissingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/MissingStorage';
};

export type MissingStorageGetAllMedicationStorageMissingsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type MissingStorageGetAllMedicationStorageMissingsError = MissingStorageGetAllMedicationStorageMissingsErrors[keyof MissingStorageGetAllMedicationStorageMissingsErrors];

export type MissingStorageGetAllMedicationStorageMissingsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationStorageMissingOutputDto;
};

export type MissingStorageGetAllMedicationStorageMissingsResponse = MissingStorageGetAllMedicationStorageMissingsResponses[keyof MissingStorageGetAllMedicationStorageMissingsResponses];

export type MissingStoragePostData = {
    body: HospitalApiDtosInputsMedicationStorageMissingInputDto;
    path?: never;
    query?: never;
    url: '/api/MissingStorage';
};

export type MissingStoragePostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MissingStorageDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/MissingStorage/{id}';
};

export type MissingStorageDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MissingStorageGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/MissingStorage/{id}';
};

export type MissingStorageGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type MissingStorageGetError = MissingStorageGetErrors[keyof MissingStorageGetErrors];

export type MissingStorageGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationStorageMissingOutputDto;
};

export type MissingStorageGetResponse = MissingStorageGetResponses[keyof MissingStorageGetResponses];

export type MissingStoragePutData = {
    body: HospitalApiDtosInputsMedicationStorageMissingInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/MissingStorage/{id}';
};

export type MissingStoragePutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatientGetAllPatientsData = {
    body?: never;
    path?: never;
    query?: {
        Firstname?: string;
        Lastname?: string;
        Gender?: string;
        CprNumber?: string;
        sortBy?: string;
        sortDir?: string;
    };
    url: '/api/Patient';
};

export type PatientGetAllPatientsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PatientGetAllPatientsError = PatientGetAllPatientsErrors[keyof PatientGetAllPatientsErrors];

export type PatientGetAllPatientsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsPatientOutputDto;
};

export type PatientGetAllPatientsResponse = PatientGetAllPatientsResponses[keyof PatientGetAllPatientsResponses];

export type PatientPostData = {
    body: HospitalApiDtosInputsPatientInputDto;
    path?: never;
    query?: never;
    url: '/api/Patient';
};

export type PatientPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatientDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Patient/{id}';
};

export type PatientDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatientGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Patient/{id}';
};

export type PatientGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PatientGetError = PatientGetErrors[keyof PatientGetErrors];

export type PatientGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsPatientOutputDto;
};

export type PatientGetResponse = PatientGetResponses[keyof PatientGetResponses];

export type PatientPutData = {
    body: HospitalApiDtosInputsPatientInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Patient/{id}';
};

export type PatientPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PrescriptionGetAllPrescriptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Prescription';
};

export type PrescriptionGetAllPrescriptionsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PrescriptionGetAllPrescriptionsError = PrescriptionGetAllPrescriptionsErrors[keyof PrescriptionGetAllPrescriptionsErrors];

export type PrescriptionGetAllPrescriptionsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsPrescriptionOutputDto;
};

export type PrescriptionGetAllPrescriptionsResponse = PrescriptionGetAllPrescriptionsResponses[keyof PrescriptionGetAllPrescriptionsResponses];

export type PrescriptionPostData = {
    body: HospitalApiDtosInputsPrescriptionInputDto;
    path?: never;
    query?: never;
    url: '/api/Prescription';
};

export type PrescriptionPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PrescriptionDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Prescription/{id}';
};

export type PrescriptionDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PrescriptionGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Prescription/{id}';
};

export type PrescriptionGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PrescriptionGetError = PrescriptionGetErrors[keyof PrescriptionGetErrors];

export type PrescriptionGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsPrescriptionOutputDto;
};

export type PrescriptionGetResponse = PrescriptionGetResponses[keyof PrescriptionGetResponses];

export type PrescriptionPutData = {
    body: HospitalApiDtosInputsPrescriptionInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Prescription/{id}';
};

export type PrescriptionPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RoomBookingGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/RoomBooking';
};

export type RoomBookingGetAllErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type RoomBookingGetAllError = RoomBookingGetAllErrors[keyof RoomBookingGetAllErrors];

export type RoomBookingGetAllResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsRoomBookingOutputDto;
};

export type RoomBookingGetAllResponse = RoomBookingGetAllResponses[keyof RoomBookingGetAllResponses];

export type RoomBookingPostData = {
    body: HospitalApiDtosInputsRoomBookingInputDto;
    path?: never;
    query?: never;
    url: '/api/RoomBooking';
};

export type RoomBookingPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RoomBookingDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/RoomBooking/{id}';
};

export type RoomBookingDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RoomBookingGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/RoomBooking/{id}';
};

export type RoomBookingGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type RoomBookingGetError = RoomBookingGetErrors[keyof RoomBookingGetErrors];

export type RoomBookingGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsRoomBookingOutputDto;
};

export type RoomBookingGetResponse = RoomBookingGetResponses[keyof RoomBookingGetResponses];

export type RoomBookingPutData = {
    body: HospitalApiDtosInputsRoomBookingInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/RoomBooking/{id}';
};

export type RoomBookingPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ShiftGetAllShiftsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        sortBy?: string;
        sortDir?: string;
    };
    url: '/api/Shift';
};

export type ShiftGetAllShiftsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type ShiftGetAllShiftsError = ShiftGetAllShiftsErrors[keyof ShiftGetAllShiftsErrors];

export type ShiftGetAllShiftsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsShiftOutputDto;
};

export type ShiftGetAllShiftsResponse = ShiftGetAllShiftsResponses[keyof ShiftGetAllShiftsResponses];

export type ShiftPostData = {
    body: HospitalApiDtosInputsShiftInputDto;
    path?: never;
    query?: never;
    url: '/api/Shift';
};

export type ShiftPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ShiftDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Shift/{id}';
};

export type ShiftDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ShiftGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Shift/{id}';
};

export type ShiftGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type ShiftGetError = ShiftGetErrors[keyof ShiftGetErrors];

export type ShiftGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsShiftOutputDto;
};

export type ShiftGetResponse = ShiftGetResponses[keyof ShiftGetResponses];

export type ShiftPutData = {
    body: HospitalApiDtosInputsShiftInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Shift/{id}';
};

export type ShiftPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StaffGetAllStaffsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Staff';
};

export type StaffGetAllStaffsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type StaffGetAllStaffsError = StaffGetAllStaffsErrors[keyof StaffGetAllStaffsErrors];

export type StaffGetAllStaffsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsStaffOutputDto;
};

export type StaffGetAllStaffsResponse = StaffGetAllStaffsResponses[keyof StaffGetAllStaffsResponses];

export type StaffPostData = {
    body: HospitalApiDtosInputsStaffInputDto;
    path?: never;
    query?: never;
    url: '/api/Staff';
};

export type StaffPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StaffDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Staff/{id}';
};

export type StaffDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StaffGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Staff/{id}';
};

export type StaffGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type StaffGetError = StaffGetErrors[keyof StaffGetErrors];

export type StaffGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsStaffOutputDto;
};

export type StaffGetResponse = StaffGetResponses[keyof StaffGetResponses];

export type StaffPutData = {
    body: HospitalApiDtosInputsStaffInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Staff/{id}';
};

export type StaffPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StorageGetAllMedicationStoragesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Storage';
};

export type StorageGetAllMedicationStoragesErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type StorageGetAllMedicationStoragesError = StorageGetAllMedicationStoragesErrors[keyof StorageGetAllMedicationStoragesErrors];

export type StorageGetAllMedicationStoragesResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationStorageOutputDto;
};

export type StorageGetAllMedicationStoragesResponse = StorageGetAllMedicationStoragesResponses[keyof StorageGetAllMedicationStoragesResponses];

export type StoragePostData = {
    body: HospitalApiDtosInputsMedicationStorageInputDto;
    path?: never;
    query?: never;
    url: '/api/Storage';
};

export type StoragePostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StorageDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Storage/{id}';
};

export type StorageDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StorageGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Storage/{id}';
};

export type StorageGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type StorageGetError = StorageGetErrors[keyof StorageGetErrors];

export type StorageGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationStorageOutputDto;
};

export type StorageGetResponse = StorageGetResponses[keyof StorageGetResponses];

export type StoragePutData = {
    body: HospitalApiDtosInputsMedicationStorageInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Storage/{id}';
};

export type StoragePutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentGetAllTreatmentsData = {
    body?: never;
    path?: never;
    query?: {
        FkPatientId?: number | string;
        Description?: string;
        Time?: string;
        sortBy?: string;
        sortDir?: string;
    };
    url: '/api/Treatment';
};

export type TreatmentGetAllTreatmentsErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type TreatmentGetAllTreatmentsError = TreatmentGetAllTreatmentsErrors[keyof TreatmentGetAllTreatmentsErrors];

export type TreatmentGetAllTreatmentsResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsTreatmentOutputDto;
};

export type TreatmentGetAllTreatmentsResponse = TreatmentGetAllTreatmentsResponses[keyof TreatmentGetAllTreatmentsResponses];

export type TreatmentPostData = {
    body: HospitalApiDtosInputsTreatmentInputDto;
    path?: never;
    query?: never;
    url: '/api/Treatment';
};

export type TreatmentPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Treatment/{id}';
};

export type TreatmentDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Treatment/{id}';
};

export type TreatmentGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type TreatmentGetError = TreatmentGetErrors[keyof TreatmentGetErrors];

export type TreatmentGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsTreatmentOutputDto;
};

export type TreatmentGetResponse = TreatmentGetResponses[keyof TreatmentGetResponses];

export type TreatmentPutData = {
    body: HospitalApiDtosInputsTreatmentInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Treatment/{id}';
};

export type TreatmentPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentStaffGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/TreatmentStaff';
};

export type TreatmentStaffGetAllErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type TreatmentStaffGetAllError = TreatmentStaffGetAllErrors[keyof TreatmentStaffGetAllErrors];

export type TreatmentStaffGetAllResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsTreatmentStaffOutputDto;
};

export type TreatmentStaffGetAllResponse = TreatmentStaffGetAllResponses[keyof TreatmentStaffGetAllResponses];

export type TreatmentStaffPostData = {
    body: HospitalApiDtosInputsTreatmentStaffInputDto;
    path?: never;
    query?: never;
    url: '/api/TreatmentStaff';
};

export type TreatmentStaffPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentStaffDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/TreatmentStaff/{id}';
};

export type TreatmentStaffDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentStaffGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/TreatmentStaff/{id}';
};

export type TreatmentStaffGetErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type TreatmentStaffGetError = TreatmentStaffGetErrors[keyof TreatmentStaffGetErrors];

export type TreatmentStaffGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsTreatmentStaffOutputDto;
};

export type TreatmentStaffGetResponse = TreatmentStaffGetResponses[keyof TreatmentStaffGetResponses];

export type TreatmentStaffPutData = {
    body: HospitalApiDtosInputsTreatmentStaffInputDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/TreatmentStaff/{id}';
};

export type TreatmentStaffPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/User';
};

export type UserGetAllErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
};

export type UserGetAllError = UserGetAllErrors[keyof UserGetAllErrors];

export type UserGetAllResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsUserOutputDto;
};

export type UserGetAllResponse = UserGetAllResponses[keyof UserGetAllResponses];

export type UserRegisterData = {
    body: HospitalApiDtosInputsRegisterInputDto;
    path?: never;
    query?: never;
    url: '/api/User/register';
};

export type UserRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserChangePasswordData = {
    body: string;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/User/{id}/password';
};

export type UserChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/User/{id}';
};

export type UserDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};
