// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type HospitalApiDtosInputsDepartmentInput = {
    name?: null | string;
    type?: null | string;
};

export type HospitalApiDtosInputsFloorInput = {
    name?: string;
    fkBuildingId?: number | string;
};

export type HospitalApiDtosInputsLoginInput = {
    username?: string;
    password?: string;
};

export type HospitalApiDtosInputsMedicationInput = {
    name?: null | string;
    genericName?: null | string;
    brand?: null | string;
    form?: null | string;
    strength?: null | string;
    category?: null | string;
    description?: null | string;
};

export type HospitalApiDtosInputsMedicationStorageInput = {
    fkMedicationId?: number | string;
    amount?: number | string;
};

export type HospitalApiDtosInputsMedicationStorageMissingInput = {
    fkMedicationStorageId?: number | string;
    amountMissing?: number | string;
    wentMissingAt?: string;
};

export type HospitalApiDtosInputsPatientInput = {
    firstname?: null | string;
    lastname?: null | string;
    gender?: null | string;
    cprNumber?: null | string;
};

export type HospitalApiDtosInputsPrescriptionInput = {
    fkMedicationId?: number | string;
    fkTreatmentId?: number | string;
    fkPrescribedByStaffId?: number | string;
    doses?: number | string;
};

export type HospitalApiDtosInputsRegisterInput = {
    username?: string;
    password?: string;
    fkStaffId?: number | string;
};

export type HospitalApiDtosInputsRoomBookingInput = {
    fkRoomId?: number | string;
    startTime?: string;
    endTime?: string;
    fkPatientId?: number | string;
};

export type HospitalApiDtosInputsShiftInput = {
    startTime?: string;
    endTime?: string;
};

export type HospitalApiDtosInputsStaffInput = {
    firstname?: null | string;
    lastname?: null | string;
    fkRoleId?: number | string;
};

export type HospitalApiDtosInputsTreatmentInput = {
    fkPatientId?: number | string;
    description?: null | string;
    time?: string;
};

export type HospitalApiDtosInputsTreatmentStaffInput = {
    fkTreatmentId?: number | string;
    fkStaffId?: number | string;
};

export type HospitalApiDtosOutputsBuildingOutput = {
    id?: number | string;
    name?: string;
    address?: null | string;
};

export type HospitalApiDtosOutputsDepartmentOutput = {
    id?: number | string;
    name?: null | string;
    type?: null | string;
};

export type HospitalApiDtosOutputsFloorOutput = {
    id?: number | string;
    name?: string;
    fkBuildingId?: number | string;
};

export type HospitalApiDtosOutputsFloorRoomsOutput = {
    floor: HospitalApiDtosOutputsFloorOutput;
    rooms: Array<HospitalApiDtosOutputsRoomOutput>;
};

export type HospitalApiDtosOutputsLocationOutput = {
    building: HospitalApiDtosOutputsBuildingOutput;
    floorsWithRooms: Array<HospitalApiDtosOutputsFloorRoomsOutput>;
};

export type HospitalApiDtosOutputsMedicationOutput = {
    id?: number | string;
    name?: null | string;
    genericName?: null | string;
    brand?: null | string;
    form?: null | string;
    strength?: null | string;
    category?: null | string;
    description?: null | string;
};

export type HospitalApiDtosOutputsMedicationStorageMissingOutput = {
    id?: number | string;
    fkMedicationStorageId?: number | string;
    amountMissing?: number | string;
    wentMissingAt?: string;
};

export type HospitalApiDtosOutputsMedicationStorageOutput = {
    id?: number | string;
    fkMedicationId?: number | string;
    amount?: number | string;
};

export type HospitalApiDtosOutputsPatientOutput = {
    id?: number | string;
    firstname?: null | string;
    lastname?: null | string;
    gender?: null | string;
    cprNumber?: null | string;
};

export type HospitalApiDtosOutputsPrescriptionOutput = {
    id?: number | string;
    fkMedicationId?: number | string;
    fkTreatmentId?: number | string;
    fkPrescribedByStaffId?: number | string;
    doses?: number | string;
};

export type HospitalApiDtosOutputsRoomBookingOutput = {
    id?: number | string;
    fkRoomId?: number | string;
    startTime?: string;
    endTime?: string;
    fkPatientId?: number | string;
};

export type HospitalApiDtosOutputsRoomOutput = {
    id?: number | string;
    name?: string;
    fkFloorId?: number | string;
};

export type HospitalApiDtosOutputsShiftOutput = {
    id?: number | string;
    startTime?: string;
    endTime?: string;
};

export type HospitalApiDtosOutputsStaffOutput = {
    id?: number | string;
    firstname?: null | string;
    lastname?: null | string;
    fkRoleId?: number | string;
};

export type HospitalApiDtosOutputsTreatmentOutput = {
    id?: number | string;
    fkPatientId?: number | string;
    description?: null | string;
    time?: string;
};

export type HospitalApiDtosOutputsTreatmentStaffOutput = {
    id?: number | string;
    fkTreatmentId?: number | string;
    fkStaffId?: number | string;
};

export type HospitalApiDtosOutputsUserOutput = {
    id?: number | string;
    username?: string;
    fkStaffId?: number | string;
};

export type AuthLoginData = {
    body: HospitalApiDtosInputsLoginInput;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type AuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DepartmentGetAllDepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Department';
};

export type DepartmentGetAllDepartmentsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsDepartmentOutput>;
};

export type DepartmentGetAllDepartmentsResponse = DepartmentGetAllDepartmentsResponses[keyof DepartmentGetAllDepartmentsResponses];

export type DepartmentPostData = {
    body: HospitalApiDtosInputsDepartmentInput;
    path?: never;
    query?: never;
    url: '/api/Department';
};

export type DepartmentPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DepartmentDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Department/{id}';
};

export type DepartmentDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DepartmentGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Department/{id}';
};

export type DepartmentGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsDepartmentOutput;
};

export type DepartmentGetResponse = DepartmentGetResponses[keyof DepartmentGetResponses];

export type DepartmentPutData = {
    body: HospitalApiDtosInputsDepartmentInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Department/{id}';
};

export type DepartmentPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ExternalMedicinePricesGetMedicineProductsByNameData = {
    body?: never;
    path?: never;
    query?: {
        productName?: string;
    };
    url: '/api/ExternalMedicinePrices/productsByName';
};

export type ExternalMedicinePricesGetMedicineProductsByNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ExternalMedicinePricesGetMedicineProductsByIngredientsData = {
    body?: never;
    path?: never;
    query?: {
        ingredientName?: string;
    };
    url: '/api/ExternalMedicinePrices/productsByIngredient';
};

export type ExternalMedicinePricesGetMedicineProductsByIngredientsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ExternalMedicinePricesGetMedicineProductDetailsData = {
    body?: never;
    path?: never;
    query?: {
        productDetailId?: string;
    };
    url: '/api/ExternalMedicinePrices/productDetails';
};

export type ExternalMedicinePricesGetMedicineProductDetailsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LocationGetAllLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Location';
};

export type LocationGetAllLocationsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsLocationOutput>;
};

export type LocationGetAllLocationsResponse = LocationGetAllLocationsResponses[keyof LocationGetAllLocationsResponses];

export type LocationGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/{id}';
};

export type LocationGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsLocationOutput;
};

export type LocationGetResponse = LocationGetResponses[keyof LocationGetResponses];

export type LocationGetAllFloorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Location/floor';
};

export type LocationGetAllFloorsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsFloorRoomsOutput>;
};

export type LocationGetAllFloorsResponse = LocationGetAllFloorsResponses[keyof LocationGetAllFloorsResponses];

export type LocationPostFloorData = {
    body: HospitalApiDtosInputsFloorInput;
    path?: never;
    query?: never;
    url: '/api/Location/floor';
};

export type LocationPostFloorResponses = {
    /**
     * OK
     */
    200: number | string;
};

export type LocationPostFloorResponse = LocationPostFloorResponses[keyof LocationPostFloorResponses];

export type LocationDeleteFloorData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/floor/{id}';
};

export type LocationDeleteFloorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LocationGetFloorData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/floor/{id}';
};

export type LocationGetFloorResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsFloorRoomsOutput;
};

export type LocationGetFloorResponse = LocationGetFloorResponses[keyof LocationGetFloorResponses];

export type LocationPutFloorData = {
    body: HospitalApiDtosInputsFloorInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Location/floor/{id}';
};

export type LocationPutFloorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MedicinGetAllMedicinsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Medicin';
};

export type MedicinGetAllMedicinsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsMedicationOutput>;
};

export type MedicinGetAllMedicinsResponse = MedicinGetAllMedicinsResponses[keyof MedicinGetAllMedicinsResponses];

export type MedicinPostData = {
    body: HospitalApiDtosInputsMedicationInput;
    path?: never;
    query?: never;
    url: '/api/Medicin';
};

export type MedicinPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MedicinDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Medicin/{id}';
};

export type MedicinDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MedicinGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Medicin/{id}';
};

export type MedicinGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationOutput;
};

export type MedicinGetResponse = MedicinGetResponses[keyof MedicinGetResponses];

export type MedicinPutData = {
    body: HospitalApiDtosInputsMedicationInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Medicin/{id}';
};

export type MedicinPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MissingStorageGetAllMedicationStorageMissingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/MissingStorage';
};

export type MissingStorageGetAllMedicationStorageMissingsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsMedicationStorageMissingOutput>;
};

export type MissingStorageGetAllMedicationStorageMissingsResponse = MissingStorageGetAllMedicationStorageMissingsResponses[keyof MissingStorageGetAllMedicationStorageMissingsResponses];

export type MissingStoragePostData = {
    body: HospitalApiDtosInputsMedicationStorageMissingInput;
    path?: never;
    query?: never;
    url: '/api/MissingStorage';
};

export type MissingStoragePostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MissingStorageDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/MissingStorage/{id}';
};

export type MissingStorageDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MissingStorageGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/MissingStorage/{id}';
};

export type MissingStorageGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationStorageMissingOutput;
};

export type MissingStorageGetResponse = MissingStorageGetResponses[keyof MissingStorageGetResponses];

export type MissingStoragePutData = {
    body: HospitalApiDtosInputsMedicationStorageMissingInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/MissingStorage/{id}';
};

export type MissingStoragePutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatientGetAllPatientsData = {
    body?: never;
    path?: never;
    query?: {
        Firstname?: string;
        Lastname?: string;
        Gender?: string;
        CprNumber?: string;
        sortBy?: string;
        sortDir?: string;
    };
    url: '/api/Patient';
};

export type PatientGetAllPatientsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsPatientOutput>;
};

export type PatientGetAllPatientsResponse = PatientGetAllPatientsResponses[keyof PatientGetAllPatientsResponses];

export type PatientPostData = {
    body: HospitalApiDtosInputsPatientInput;
    path?: never;
    query?: never;
    url: '/api/Patient';
};

export type PatientPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatientDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Patient/{id}';
};

export type PatientDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatientGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Patient/{id}';
};

export type PatientGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsPatientOutput;
};

export type PatientGetResponse = PatientGetResponses[keyof PatientGetResponses];

export type PatientPutData = {
    body: HospitalApiDtosInputsPatientInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Patient/{id}';
};

export type PatientPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PrescriptionGetAllPrescriptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Prescription';
};

export type PrescriptionGetAllPrescriptionsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsPrescriptionOutput>;
};

export type PrescriptionGetAllPrescriptionsResponse = PrescriptionGetAllPrescriptionsResponses[keyof PrescriptionGetAllPrescriptionsResponses];

export type PrescriptionPostData = {
    body: HospitalApiDtosInputsPrescriptionInput;
    path?: never;
    query?: never;
    url: '/api/Prescription';
};

export type PrescriptionPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PrescriptionDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Prescription/{id}';
};

export type PrescriptionDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PrescriptionGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Prescription/{id}';
};

export type PrescriptionGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsPrescriptionOutput;
};

export type PrescriptionGetResponse = PrescriptionGetResponses[keyof PrescriptionGetResponses];

export type PrescriptionPutData = {
    body: HospitalApiDtosInputsPrescriptionInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Prescription/{id}';
};

export type PrescriptionPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RoomBookingGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/RoomBooking';
};

export type RoomBookingGetAllResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsRoomBookingOutput>;
};

export type RoomBookingGetAllResponse = RoomBookingGetAllResponses[keyof RoomBookingGetAllResponses];

export type RoomBookingPostData = {
    body: HospitalApiDtosInputsRoomBookingInput;
    path?: never;
    query?: never;
    url: '/api/RoomBooking';
};

export type RoomBookingPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RoomBookingDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/RoomBooking/{id}';
};

export type RoomBookingDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RoomBookingGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/RoomBooking/{id}';
};

export type RoomBookingGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsRoomBookingOutput;
};

export type RoomBookingGetResponse = RoomBookingGetResponses[keyof RoomBookingGetResponses];

export type RoomBookingPutData = {
    body: HospitalApiDtosInputsRoomBookingInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/RoomBooking/{id}';
};

export type RoomBookingPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ShiftGetAllShiftsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        sortBy?: string;
        sortDir?: string;
    };
    url: '/api/Shift';
};

export type ShiftGetAllShiftsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsShiftOutput>;
};

export type ShiftGetAllShiftsResponse = ShiftGetAllShiftsResponses[keyof ShiftGetAllShiftsResponses];

export type ShiftPostData = {
    body: HospitalApiDtosInputsShiftInput;
    path?: never;
    query?: never;
    url: '/api/Shift';
};

export type ShiftPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ShiftDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Shift/{id}';
};

export type ShiftDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ShiftGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Shift/{id}';
};

export type ShiftGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsShiftOutput;
};

export type ShiftGetResponse = ShiftGetResponses[keyof ShiftGetResponses];

export type ShiftPutData = {
    body: HospitalApiDtosInputsShiftInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Shift/{id}';
};

export type ShiftPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StaffGetAllStaffsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Staff';
};

export type StaffGetAllStaffsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsStaffOutput>;
};

export type StaffGetAllStaffsResponse = StaffGetAllStaffsResponses[keyof StaffGetAllStaffsResponses];

export type StaffPostData = {
    body: HospitalApiDtosInputsStaffInput;
    path?: never;
    query?: never;
    url: '/api/Staff';
};

export type StaffPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StaffDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Staff/{id}';
};

export type StaffDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StaffGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Staff/{id}';
};

export type StaffGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsStaffOutput;
};

export type StaffGetResponse = StaffGetResponses[keyof StaffGetResponses];

export type StaffPutData = {
    body: HospitalApiDtosInputsStaffInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Staff/{id}';
};

export type StaffPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StorageGetAllMedicationStoragesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Storage';
};

export type StorageGetAllMedicationStoragesResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsMedicationStorageOutput>;
};

export type StorageGetAllMedicationStoragesResponse = StorageGetAllMedicationStoragesResponses[keyof StorageGetAllMedicationStoragesResponses];

export type StoragePostData = {
    body: HospitalApiDtosInputsMedicationStorageInput;
    path?: never;
    query?: never;
    url: '/api/Storage';
};

export type StoragePostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StorageDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Storage/{id}';
};

export type StorageDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StorageGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Storage/{id}';
};

export type StorageGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsMedicationStorageOutput;
};

export type StorageGetResponse = StorageGetResponses[keyof StorageGetResponses];

export type StoragePutData = {
    body: HospitalApiDtosInputsMedicationStorageInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Storage/{id}';
};

export type StoragePutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentGetAllTreatmentsData = {
    body?: never;
    path?: never;
    query?: {
        FkPatientId?: number | string;
        Description?: string;
        Time?: string;
        sortBy?: string;
        sortDir?: string;
    };
    url: '/api/Treatment';
};

export type TreatmentGetAllTreatmentsResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsTreatmentOutput>;
};

export type TreatmentGetAllTreatmentsResponse = TreatmentGetAllTreatmentsResponses[keyof TreatmentGetAllTreatmentsResponses];

export type TreatmentPostData = {
    body: HospitalApiDtosInputsTreatmentInput;
    path?: never;
    query?: never;
    url: '/api/Treatment';
};

export type TreatmentPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Treatment/{id}';
};

export type TreatmentDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Treatment/{id}';
};

export type TreatmentGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsTreatmentOutput;
};

export type TreatmentGetResponse = TreatmentGetResponses[keyof TreatmentGetResponses];

export type TreatmentPutData = {
    body: HospitalApiDtosInputsTreatmentInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/Treatment/{id}';
};

export type TreatmentPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentStaffGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/TreatmentStaff';
};

export type TreatmentStaffGetAllResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsTreatmentStaffOutput>;
};

export type TreatmentStaffGetAllResponse = TreatmentStaffGetAllResponses[keyof TreatmentStaffGetAllResponses];

export type TreatmentStaffPostData = {
    body: HospitalApiDtosInputsTreatmentStaffInput;
    path?: never;
    query?: never;
    url: '/api/TreatmentStaff';
};

export type TreatmentStaffPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentStaffDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/TreatmentStaff/{id}';
};

export type TreatmentStaffDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TreatmentStaffGetData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/TreatmentStaff/{id}';
};

export type TreatmentStaffGetResponses = {
    /**
     * OK
     */
    200: HospitalApiDtosOutputsTreatmentStaffOutput;
};

export type TreatmentStaffGetResponse = TreatmentStaffGetResponses[keyof TreatmentStaffGetResponses];

export type TreatmentStaffPutData = {
    body: HospitalApiDtosInputsTreatmentStaffInput;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/TreatmentStaff/{id}';
};

export type TreatmentStaffPutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/User';
};

export type UserGetAllResponses = {
    /**
     * OK
     */
    200: Array<HospitalApiDtosOutputsUserOutput>;
};

export type UserGetAllResponse = UserGetAllResponses[keyof UserGetAllResponses];

export type UserRegisterData = {
    body: HospitalApiDtosInputsRegisterInput;
    path?: never;
    query?: never;
    url: '/api/User/register';
};

export type UserRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserChangePasswordData = {
    body: string;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/User/{id}/password';
};

export type UserChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserDeleteData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/User/{id}';
};

export type UserDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};
