// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zHospitalApiDtosExternalMedicineDetailOutput = z.object({
    navn: z.string().nullish(),
    varenummer: z.string().nullish(),
    styrke: z.string().nullish(),
    pakning: z.string().nullish(),
    virksomtStof: z.string().nullish(),
    firma: z.string().nullish(),
    atcKode: z.string().nullish(),
    dosisdispensering: z.boolean().optional(),
    udleveringsgruppe: z.string().nullish(),
    prisPrPakning: z.string().nullish(),
    prisPrEnhed: z.string().nullish(),
    aip: z.string().nullish(),
    tilskudBeregnesAf: z.string().nullish(),
    udgaaet: z.boolean().optional(),
    udgaaetDato: z.string().nullish(),
    dosering: z.string().nullish(),
    indikation: z.string().nullish(),
    trafikAdvarsel: z.boolean().optional(),
    ddd: z.string().nullish(),
    opbevaringsbetingelser: z.string().nullish(),
    nbsSpeciale: z.string().nullish(),
    haandkoeb: z.boolean().optional(),
    tilskudKode: z.string().nullish(),
    tilskudTekst: z.string().nullish()
});

export const zHospitalApiDtosExternalMedicineProductOutput = z.object({
    navn: z.string(),
    varenummer: z.string(),
    firma: z.string(),
    styrke: z.string(),
    detaljer: z.string(),
    pakning: z.string()
});

export const zHospitalApiDtosInputsDepartmentInput = z.object({
    name: z.string().min(2).max(100).nullish(),
    type: z.string().min(2).max(100).nullish()
});

export const zHospitalApiDtosInputsFloorInput = z.object({
    name: z.string().min(2).max(100).optional(),
    fkBuildingId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosInputsLoginInput = z.object({
    username: z.string().min(2).max(100).optional(),
    password: z.string().min(8).max(40).optional()
});

export const zHospitalApiDtosInputsMedicationInput = z.object({
    name: z.string().min(2).max(100).nullish(),
    genericName: z.string().min(2).max(100).nullish(),
    brand: z.string().min(2).max(100).nullish(),
    form: z.string().min(2).max(100).nullish(),
    strength: z.string().min(2).max(100).nullish(),
    category: z.string().min(2).max(100).nullish(),
    description: z.string().nullish()
});

export const zHospitalApiDtosInputsMedicationStorageInput = z.object({
    fkMedicationId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    amount: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/)
    ]).optional()
});

export const zHospitalApiDtosInputsMedicationStorageMissingInput = z.object({
    fkMedicationStorageId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    amountMissing: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/)
    ]).optional(),
    wentMissingAt: z.iso.datetime().optional()
});

export const zHospitalApiDtosInputsPatientInput = z.object({
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    gender: z.string().min(2).max(50).nullish(),
    cprNumber: z.string().min(0).max(10).nullish()
});

export const zHospitalApiDtosInputsPrescriptionInput = z.object({
    fkMedicationId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkTreatmentId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkPrescribedByStaffId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    doses: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/)
    ]).optional()
});

export const zHospitalApiDtosInputsRegisterInput = z.object({
    username: z.string().min(2).max(100).optional(),
    password: z.string().min(8).max(40).optional(),
    fkStaffId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosInputsRoomBookingInput = z.object({
    fkRoomId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional(),
    fkPatientId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosInputsShiftInput = z.object({
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional()
});

export const zHospitalApiDtosInputsStaffInput = z.object({
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    fkRoleId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosInputsTreatmentInput = z.object({
    fkPatientId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    description: z.string().min(2).max(500).nullish(),
    time: z.iso.datetime().optional()
});

export const zHospitalApiDtosInputsTreatmentStaffInput = z.object({
    fkTreatmentId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkStaffId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsBuildingOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    name: z.string().min(2).max(100).optional(),
    address: z.string().min(2).max(255).nullish()
});

export const zHospitalApiDtosOutputsDepartmentOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    name: z.string().min(2).max(100).nullish(),
    type: z.string().min(2).max(100).nullish()
});

export const zHospitalApiDtosOutputsFloorOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    name: z.string().min(2).max(100).optional(),
    fkBuildingId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsLoginOutput = z.object({
    token: z.string().min(0).max(255),
    staffId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    role: z.string().optional()
});

export const zHospitalApiDtosOutputsMedicationOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    name: z.string().min(2).max(100).nullish(),
    genericName: z.string().min(2).max(100).nullish(),
    brand: z.string().min(2).max(100).nullish(),
    form: z.string().min(2).max(100).nullish(),
    strength: z.string().min(2).max(100).nullish(),
    category: z.string().min(2).max(100).nullish(),
    description: z.string().nullish()
});

export const zHospitalApiDtosOutputsMedicationStorageMissingOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkMedicationStorageId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    amountMissing: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/)
    ]).optional(),
    wentMissingAt: z.iso.datetime().optional()
});

export const zHospitalApiDtosOutputsMedicationStorageOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkMedicationId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    amount: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsPatientOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    gender: z.string().min(2).max(50).nullish(),
    cprNumber: z.string().min(0).max(10).nullish()
});

export const zHospitalApiDtosOutputsPrescriptionOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkMedicationId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkTreatmentId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkPrescribedByStaffId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    doses: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsRoomBookingOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkRoomId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional(),
    fkPatientId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsRoomOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    name: z.string().optional(),
    fkFloorId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsFloorRoomsOutput = z.object({
    floor: zHospitalApiDtosOutputsFloorOutput,
    rooms: z.array(zHospitalApiDtosOutputsRoomOutput)
});

export const zHospitalApiDtosOutputsLocationOutput = z.object({
    building: zHospitalApiDtosOutputsBuildingOutput,
    floorsWithRooms: z.array(zHospitalApiDtosOutputsFloorRoomsOutput)
});

export const zHospitalApiDtosOutputsShiftOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional()
});

export const zHospitalApiDtosOutputsStaffOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    fkRoleId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsTreatmentOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkPatientId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    description: z.string().min(2).max(500).nullish(),
    time: z.iso.datetime().optional()
});

export const zHospitalApiDtosOutputsTreatmentStaffOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkTreatmentId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    fkStaffId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zHospitalApiDtosOutputsUserOutput = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    username: z.string().min(2).max(100).optional(),
    fkStaffId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional()
});

export const zMicrosoftAspNetCoreMvcProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish()
});

export const zAuthLoginBody = zHospitalApiDtosInputsLoginInput;

/**
 * OK
 */
export const zAuthLoginResponse = zHospitalApiDtosOutputsLoginOutput;

/**
 * OK
 */
export const zDepartmentGetAllDepartmentsResponse = z.array(zHospitalApiDtosOutputsDepartmentOutput);

export const zDepartmentPostBody = zHospitalApiDtosInputsDepartmentInput;

export const zDepartmentDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zDepartmentGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zDepartmentGetResponse = zHospitalApiDtosOutputsDepartmentOutput;

export const zDepartmentPutBody = zHospitalApiDtosInputsDepartmentInput;

export const zDepartmentPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zExternalMedicinePricesGetMedicineProductsByNameQuery = z.object({
    productName: z.string().optional()
});

/**
 * OK
 */
export const zExternalMedicinePricesGetMedicineProductsByNameResponse = zHospitalApiDtosExternalMedicineProductOutput;

export const zExternalMedicinePricesGetMedicineProductsByIngredientsQuery = z.object({
    ingredientName: z.string().optional()
});

/**
 * OK
 */
export const zExternalMedicinePricesGetMedicineProductsByIngredientsResponse = zHospitalApiDtosExternalMedicineProductOutput;

export const zExternalMedicinePricesGetMedicineProductDetailsQuery = z.object({
    productDetailId: z.string().optional()
});

/**
 * OK
 */
export const zExternalMedicinePricesGetMedicineProductDetailsResponse = zHospitalApiDtosExternalMedicineDetailOutput;

/**
 * OK
 */
export const zLocationGetAllLocationsResponse = zHospitalApiDtosOutputsLocationOutput;

export const zLocationGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zLocationGetResponse = zHospitalApiDtosOutputsLocationOutput;

/**
 * OK
 */
export const zLocationGetAllFloorsResponse = zHospitalApiDtosOutputsFloorRoomsOutput;

export const zLocationPostFloorBody = zHospitalApiDtosInputsFloorInput;

/**
 * OK
 */
export const zLocationPostFloorResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/)
]);

export const zLocationDeleteFloorPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zLocationGetFloorPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zLocationGetFloorResponse = zHospitalApiDtosOutputsFloorRoomsOutput;

export const zLocationPutFloorBody = zHospitalApiDtosInputsFloorInput;

export const zLocationPutFloorPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zMedicinGetAllMedicinsResponse = zHospitalApiDtosOutputsMedicationOutput;

export const zMedicinPostBody = zHospitalApiDtosInputsMedicationInput;

export const zMedicinDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zMedicinGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zMedicinGetResponse = zHospitalApiDtosOutputsMedicationOutput;

export const zMedicinPutBody = zHospitalApiDtosInputsMedicationInput;

export const zMedicinPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zMissingStorageGetAllMedicationStorageMissingsResponse = zHospitalApiDtosOutputsMedicationStorageMissingOutput;

export const zMissingStoragePostBody = zHospitalApiDtosInputsMedicationStorageMissingInput;

export const zMissingStorageDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zMissingStorageGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zMissingStorageGetResponse = zHospitalApiDtosOutputsMedicationStorageMissingOutput;

export const zMissingStoragePutBody = zHospitalApiDtosInputsMedicationStorageMissingInput;

export const zMissingStoragePutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zPatientGetAllPatientsQuery = z.object({
    Firstname: z.string().min(2).max(100).optional(),
    Lastname: z.string().min(2).max(100).optional(),
    Gender: z.string().min(2).max(50).optional(),
    CprNumber: z.string().min(0).max(10).optional(),
    sortBy: z.string().optional(),
    sortDir: z.string().optional().default('asc')
});

/**
 * OK
 */
export const zPatientGetAllPatientsResponse = zHospitalApiDtosOutputsPatientOutput;

export const zPatientPostBody = zHospitalApiDtosInputsPatientInput;

export const zPatientDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zPatientGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zPatientGetResponse = zHospitalApiDtosOutputsPatientOutput;

export const zPatientPutBody = zHospitalApiDtosInputsPatientInput;

export const zPatientPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zPrescriptionGetAllPrescriptionsResponse = zHospitalApiDtosOutputsPrescriptionOutput;

export const zPrescriptionPostBody = zHospitalApiDtosInputsPrescriptionInput;

export const zPrescriptionDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zPrescriptionGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zPrescriptionGetResponse = zHospitalApiDtosOutputsPrescriptionOutput;

export const zPrescriptionPutBody = zHospitalApiDtosInputsPrescriptionInput;

export const zPrescriptionPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zRoomBookingGetAllResponse = zHospitalApiDtosOutputsRoomBookingOutput;

export const zRoomBookingPostBody = zHospitalApiDtosInputsRoomBookingInput;

export const zRoomBookingDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zRoomBookingGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zRoomBookingGetResponse = zHospitalApiDtosOutputsRoomBookingOutput;

export const zRoomBookingPutBody = zHospitalApiDtosInputsRoomBookingInput;

export const zRoomBookingPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zShiftGetAllShiftsQuery = z.object({
    from: z.iso.datetime().optional(),
    to: z.iso.datetime().optional(),
    sortBy: z.string().optional(),
    sortDir: z.string().optional().default('asc')
});

/**
 * OK
 */
export const zShiftGetAllShiftsResponse = zHospitalApiDtosOutputsShiftOutput;

export const zShiftPostBody = zHospitalApiDtosInputsShiftInput;

export const zShiftDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zShiftGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zShiftGetResponse = zHospitalApiDtosOutputsShiftOutput;

export const zShiftPutBody = zHospitalApiDtosInputsShiftInput;

export const zShiftPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zStaffGetAllStaffsResponse = zHospitalApiDtosOutputsStaffOutput;

export const zStaffPostBody = zHospitalApiDtosInputsStaffInput;

export const zStaffDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zStaffGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zStaffGetResponse = zHospitalApiDtosOutputsStaffOutput;

export const zStaffPutBody = zHospitalApiDtosInputsStaffInput;

export const zStaffPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zStorageGetAllMedicationStoragesResponse = zHospitalApiDtosOutputsMedicationStorageOutput;

export const zStoragePostBody = zHospitalApiDtosInputsMedicationStorageInput;

export const zStorageDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zStorageGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zStorageGetResponse = zHospitalApiDtosOutputsMedicationStorageOutput;

export const zStoragePutBody = zHospitalApiDtosInputsMedicationStorageInput;

export const zStoragePutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zTreatmentGetAllTreatmentsQuery = z.object({
    FkPatientId: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).optional(),
    Description: z.string().min(2).max(500).optional(),
    Time: z.iso.datetime().optional(),
    sortBy: z.string().optional(),
    sortDir: z.string().optional().default('asc')
});

/**
 * OK
 */
export const zTreatmentGetAllTreatmentsResponse = zHospitalApiDtosOutputsTreatmentOutput;

export const zTreatmentPostBody = zHospitalApiDtosInputsTreatmentInput;

export const zTreatmentDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zTreatmentGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zTreatmentGetResponse = zHospitalApiDtosOutputsTreatmentOutput;

export const zTreatmentPutBody = zHospitalApiDtosInputsTreatmentInput;

export const zTreatmentPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zTreatmentStaffGetAllResponse = zHospitalApiDtosOutputsTreatmentStaffOutput;

export const zTreatmentStaffPostBody = zHospitalApiDtosInputsTreatmentStaffInput;

export const zTreatmentStaffDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zTreatmentStaffGetPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zTreatmentStaffGetResponse = zHospitalApiDtosOutputsTreatmentStaffOutput;

export const zTreatmentStaffPutBody = zHospitalApiDtosInputsTreatmentStaffInput;

export const zTreatmentStaffPutPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

/**
 * OK
 */
export const zUserGetAllResponse = zHospitalApiDtosOutputsUserOutput;

export const zUserRegisterBody = zHospitalApiDtosInputsRegisterInput;

export const zUserChangePasswordBody = z.string();

export const zUserChangePasswordPath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zUserDeletePath = z.object({
    id: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});
