// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zHospitalApiDtosExternalMedicineDetailOutputDto = z.object({
    navn: z.string().nullish(),
    varenummer: z.string().nullish(),
    styrke: z.string().nullish(),
    pakning: z.string().nullish(),
    virksomtStof: z.string().nullish(),
    firma: z.string().nullish(),
    atcKode: z.string().nullish(),
    dosisdispensering: z.boolean().optional(),
    udleveringsgruppe: z.string().nullish(),
    prisPrPakning: z.string().nullish(),
    prisPrEnhed: z.string().nullish(),
    aip: z.string().nullish(),
    tilskudBeregnesAf: z.string().nullish(),
    udgaaet: z.boolean().optional(),
    udgaaetDato: z.string().nullish(),
    dosering: z.string().nullish(),
    indikation: z.string().nullish(),
    trafikAdvarsel: z.boolean().optional(),
    ddd: z.string().nullish(),
    opbevaringsbetingelser: z.string().nullish(),
    nbsSpeciale: z.string().nullish(),
    haandkoeb: z.boolean().optional(),
    tilskudKode: z.string().nullish(),
    tilskudTekst: z.string().nullish()
});

export const zHospitalApiDtosExternalMedicineProductOutputDto = z.object({
    navn: z.string(),
    varenummer: z.string(),
    firma: z.string(),
    styrke: z.string(),
    detaljer: z.string(),
    pakning: z.string()
});

export const zHospitalApiDtosInputsDepartmentInputDto = z.object({
    name: z.string().min(2).max(100).nullish(),
    type: z.string().min(2).max(100).nullish()
});

export const zHospitalApiDtosInputsFloorInputDto = z.object({
    name: z.string().min(2).max(100).optional(),
    fkBuildingId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosInputsLoginInputDto = z.object({
    username: z.string().min(2).max(100).optional(),
    password: z.string().min(8).max(40).optional()
});

export const zHospitalApiDtosInputsMedicationInputDto = z.object({
    name: z.string().min(2).max(100).nullish(),
    genericName: z.string().min(2).max(100).nullish(),
    brand: z.string().min(2).max(100).nullish(),
    form: z.string().min(2).max(100).nullish(),
    strength: z.string().min(2).max(100).nullish(),
    category: z.string().min(2).max(100).nullish(),
    description: z.string().nullish()
});

export const zHospitalApiDtosInputsMedicationStorageInputDto = z.object({
    fkMedicationId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    amount: z.number().optional()
});

export const zHospitalApiDtosInputsMedicationStorageMissingInputDto = z.object({
    fkMedicationStorageId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    amountMissing: z.number().optional(),
    wentMissingAt: z.iso.datetime().optional()
});

export const zHospitalApiDtosInputsPatientInputDto = z.object({
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    gender: z.string().min(2).max(50).nullish(),
    cprNumber: z.string().min(0).max(10).nullish()
});

export const zHospitalApiDtosInputsPrescriptionInputDto = z.object({
    fkMedicationId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkTreatmentId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkPrescribedByStaffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    doses: z.number().optional()
});

export const zHospitalApiDtosInputsRegisterInputDto = z.object({
    username: z.string().min(2).max(100).optional(),
    password: z.string().min(8).max(40).optional(),
    fkStaffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosInputsRoomBookingInputDto = z.object({
    fkRoomId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional(),
    fkPatientId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosInputsShiftInputDto = z.object({
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional()
});

export const zHospitalApiDtosInputsStaffInputDto = z.object({
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    fkRoleId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosInputsTreatmentInputDto = z.object({
    fkPatientId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    description: z.string().min(2).max(500).nullish(),
    time: z.iso.datetime().optional()
});

export const zHospitalApiDtosInputsTreatmentStaffInputDto = z.object({
    fkTreatmentId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkStaffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosOutputsBuildingOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    name: z.string().min(2).max(100).optional(),
    address: z.string().min(2).max(255).nullish()
});

export const zHospitalApiDtosOutputsDepartmentOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    name: z.string().min(2).max(100).nullish(),
    type: z.string().min(2).max(100).nullish()
});

export const zHospitalApiDtosOutputsFloorOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    name: z.string().min(2).max(100).optional(),
    fkBuildingId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosOutputsLoginOutputDto = z.object({
    token: z.string().min(0).max(255),
    staffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    role: z.string().optional()
});

export const zHospitalApiDtosOutputsMedicationOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    name: z.string().min(2).max(100).nullish(),
    genericName: z.string().min(2).max(100).nullish(),
    brand: z.string().min(2).max(100).nullish(),
    form: z.string().min(2).max(100).nullish(),
    strength: z.string().min(2).max(100).nullish(),
    category: z.string().min(2).max(100).nullish(),
    description: z.string().nullish()
});

export const zHospitalApiDtosOutputsMedicationStorageMissingOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkMedicationStorageId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    amountMissing: z.number().optional(),
    wentMissingAt: z.iso.datetime().optional()
});

export const zHospitalApiDtosOutputsMedicationStorageOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkMedicationId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    amount: z.number().optional()
});

export const zHospitalApiDtosOutputsPatientOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    gender: z.string().min(2).max(50).nullish(),
    cprNumber: z.string().min(0).max(10).nullish()
});

export const zHospitalApiDtosOutputsPrescriptionOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkMedicationId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkTreatmentId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkPrescribedByStaffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    doses: z.number().optional()
});

export const zHospitalApiDtosOutputsRoomBookingOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkRoomId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional(),
    fkPatientId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosOutputsRoomOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    name: z.string().optional(),
    fkFloorId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosOutputsFloorRoomsOutputDto = z.object({
    floor: zHospitalApiDtosOutputsFloorOutputDto,
    rooms: z.array(zHospitalApiDtosOutputsRoomOutputDto)
});

export const zHospitalApiDtosOutputsLocationOutputDto = z.object({
    building: zHospitalApiDtosOutputsBuildingOutputDto,
    floorsWithRooms: z.array(zHospitalApiDtosOutputsFloorRoomsOutputDto)
});

export const zHospitalApiDtosOutputsShiftOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    startTime: z.iso.datetime().optional(),
    endTime: z.iso.datetime().optional()
});

export const zHospitalApiDtosOutputsStaffOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    firstname: z.string().min(2).max(100).nullish(),
    lastname: z.string().min(2).max(100).nullish(),
    fkRoleId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosOutputsTreatmentOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkPatientId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    description: z.string().min(2).max(500).nullish(),
    time: z.iso.datetime().optional()
});

export const zHospitalApiDtosOutputsTreatmentStaffOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkTreatmentId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    fkStaffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zHospitalApiDtosOutputsUserOutputDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    username: z.string().min(2).max(100).optional(),
    fkStaffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zMicrosoftAspNetCoreMvcProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish()
});

export const zAuthLoginBody = zHospitalApiDtosInputsLoginInputDto;

/**
 * OK
 */
export const zAuthLoginResponse = zHospitalApiDtosOutputsLoginOutputDto;

/**
 * OK
 */
export const zDepartmentGetAllDepartmentsResponse = z.array(zHospitalApiDtosOutputsDepartmentOutputDto);

export const zDepartmentPostBody = zHospitalApiDtosInputsDepartmentInputDto;

export const zDepartmentPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zDepartmentDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zDepartmentGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zDepartmentGetResponse = zHospitalApiDtosOutputsDepartmentOutputDto;

export const zDepartmentPutBody = zHospitalApiDtosInputsDepartmentInputDto;

export const zDepartmentPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zExternalMedicinePricesGetMedicineProductsByNameQuery = z.object({
    productName: z.string().optional()
});

/**
 * OK
 */
export const zExternalMedicinePricesGetMedicineProductsByNameResponse = z.array(zHospitalApiDtosExternalMedicineProductOutputDto);

export const zExternalMedicinePricesGetMedicineProductsByIngredientsQuery = z.object({
    ingredientName: z.string().optional()
});

/**
 * OK
 */
export const zExternalMedicinePricesGetMedicineProductsByIngredientsResponse = z.array(zHospitalApiDtosExternalMedicineProductOutputDto);

export const zExternalMedicinePricesGetMedicineProductDetailsQuery = z.object({
    productDetailId: z.string().optional()
});

/**
 * OK
 */
export const zExternalMedicinePricesGetMedicineProductDetailsResponse = zHospitalApiDtosExternalMedicineDetailOutputDto;

/**
 * OK
 */
export const zLocationGetAllLocationsResponse = z.array(zHospitalApiDtosOutputsLocationOutputDto);

export const zLocationGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zLocationGetResponse = zHospitalApiDtosOutputsLocationOutputDto;

/**
 * OK
 */
export const zLocationGetAllFloorsResponse = z.array(zHospitalApiDtosOutputsFloorRoomsOutputDto);

export const zLocationPostFloorBody = zHospitalApiDtosInputsFloorInputDto;

/**
 * OK
 */
export const zLocationPostFloorResponse = z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' });

export const zLocationDeleteFloorPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zLocationGetFloorPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zLocationGetFloorResponse = zHospitalApiDtosOutputsFloorRoomsOutputDto;

export const zLocationPutFloorBody = zHospitalApiDtosInputsFloorInputDto;

export const zLocationPutFloorPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * No Content
 */
export const zLocationPutFloorResponse = z.void();

/**
 * OK
 */
export const zMedicinGetAllMedicinsResponse = z.array(zHospitalApiDtosOutputsMedicationOutputDto);

export const zMedicinPostBody = zHospitalApiDtosInputsMedicationInputDto;

export const zMedicinPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zMedicinDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zMedicinGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zMedicinGetResponse = zHospitalApiDtosOutputsMedicationOutputDto;

export const zMedicinPutBody = zHospitalApiDtosInputsMedicationInputDto;

export const zMedicinPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zMissingStorageGetAllMedicationStorageMissingsResponse = z.array(zHospitalApiDtosOutputsMedicationStorageMissingOutputDto);

export const zMissingStoragePostBody = zHospitalApiDtosInputsMedicationStorageMissingInputDto;

export const zMissingStoragePostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zMissingStorageDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zMissingStorageGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zMissingStorageGetResponse = zHospitalApiDtosOutputsMedicationStorageMissingOutputDto;

export const zMissingStoragePutBody = zHospitalApiDtosInputsMedicationStorageMissingInputDto;

export const zMissingStoragePutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zPatientGetAllPatientsQuery = z.object({
    Firstname: z.string().min(2).max(100).optional(),
    Lastname: z.string().min(2).max(100).optional(),
    Gender: z.string().min(2).max(50).optional(),
    CprNumber: z.string().min(0).max(10).optional(),
    sortBy: z.string().optional(),
    sortDir: z.string().optional().default('asc')
});

/**
 * OK
 */
export const zPatientGetAllPatientsResponse = z.array(zHospitalApiDtosOutputsPatientOutputDto);

export const zPatientPostBody = zHospitalApiDtosInputsPatientInputDto;

export const zPatientPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zPatientDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zPatientGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zPatientGetResponse = zHospitalApiDtosOutputsPatientOutputDto;

export const zPatientPutBody = zHospitalApiDtosInputsPatientInputDto;

export const zPatientPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zPrescriptionGetAllPrescriptionsResponse = z.array(zHospitalApiDtosOutputsPrescriptionOutputDto);

export const zPrescriptionPostBody = zHospitalApiDtosInputsPrescriptionInputDto;

export const zPrescriptionPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zPrescriptionDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zPrescriptionGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zPrescriptionGetResponse = zHospitalApiDtosOutputsPrescriptionOutputDto;

export const zPrescriptionPutBody = zHospitalApiDtosInputsPrescriptionInputDto;

export const zPrescriptionPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zRoomBookingGetAllResponse = z.array(zHospitalApiDtosOutputsRoomBookingOutputDto);

export const zRoomBookingPostBody = zHospitalApiDtosInputsRoomBookingInputDto;

export const zRoomBookingPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zRoomBookingDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zRoomBookingGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zRoomBookingGetResponse = zHospitalApiDtosOutputsRoomBookingOutputDto;

export const zRoomBookingPutBody = zHospitalApiDtosInputsRoomBookingInputDto;

export const zRoomBookingPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zShiftGetAllShiftsQuery = z.object({
    from: z.iso.datetime().optional(),
    to: z.iso.datetime().optional(),
    sortBy: z.string().optional(),
    sortDir: z.string().optional().default('asc')
});

/**
 * OK
 */
export const zShiftGetAllShiftsResponse = z.array(zHospitalApiDtosOutputsShiftOutputDto);

export const zShiftPostBody = zHospitalApiDtosInputsShiftInputDto;

export const zShiftPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zShiftDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zShiftGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zShiftGetResponse = zHospitalApiDtosOutputsShiftOutputDto;

export const zShiftPutBody = zHospitalApiDtosInputsShiftInputDto;

export const zShiftPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zStaffGetAllStaffsResponse = z.array(zHospitalApiDtosOutputsStaffOutputDto);

export const zStaffPostBody = zHospitalApiDtosInputsStaffInputDto;

export const zStaffPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zStaffDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zStaffGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zStaffGetResponse = zHospitalApiDtosOutputsStaffOutputDto;

export const zStaffPutBody = zHospitalApiDtosInputsStaffInputDto;

export const zStaffPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zStorageGetAllMedicationStoragesResponse = z.array(zHospitalApiDtosOutputsMedicationStorageOutputDto);

export const zStoragePostBody = zHospitalApiDtosInputsMedicationStorageInputDto;

export const zStoragePostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zStorageDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zStorageGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zStorageGetResponse = zHospitalApiDtosOutputsMedicationStorageOutputDto;

export const zStoragePutBody = zHospitalApiDtosInputsMedicationStorageInputDto;

export const zStoragePutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zTreatmentGetAllTreatmentsQuery = z.object({
    FkPatientId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    Description: z.string().min(2).max(500).optional(),
    Time: z.iso.datetime().optional(),
    sortBy: z.string().optional(),
    sortDir: z.string().optional().default('asc')
});

/**
 * OK
 */
export const zTreatmentGetAllTreatmentsResponse = z.array(zHospitalApiDtosOutputsTreatmentOutputDto);

export const zTreatmentPostBody = zHospitalApiDtosInputsTreatmentInputDto;

export const zTreatmentPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zTreatmentDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zTreatmentGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zTreatmentGetResponse = zHospitalApiDtosOutputsTreatmentOutputDto;

export const zTreatmentPutBody = zHospitalApiDtosInputsTreatmentInputDto;

export const zTreatmentPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zTreatmentStaffGetAllResponse = z.array(zHospitalApiDtosOutputsTreatmentStaffOutputDto);

export const zTreatmentStaffPostBody = zHospitalApiDtosInputsTreatmentStaffInputDto;

export const zTreatmentStaffPostResponse = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.void()
]);

export const zTreatmentStaffDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zTreatmentStaffGetPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zTreatmentStaffGetResponse = zHospitalApiDtosOutputsTreatmentStaffOutputDto;

export const zTreatmentStaffPutBody = zHospitalApiDtosInputsTreatmentStaffInputDto;

export const zTreatmentStaffPutPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zUserGetAllResponse = zHospitalApiDtosOutputsUserOutputDto;

export const zUserRegisterBody = zHospitalApiDtosInputsRegisterInputDto;

export const zUserRegisterResponse = z.union([
    z.boolean(),
    z.void()
]);

export const zUserChangePasswordBody = z.string();

export const zUserChangePasswordPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zUserDeletePath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});
